sudo: required
services:
  - docker

before_install:
  - docker build -t stefan1982/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stefan1982/react-test npm test
  # - docker run stefan1982/react-test npm test -- --coverage

after_success:
  - docker build -t stefan1982/multi-client ./client
  - docker build -t stefan1982/multi-nginx ./nginx
  - docker build -t stefan1982/multi-server ./server
  - docker build -t stefan1982/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take those images and push them to docker hub
  - docker push stefan1982/multi-client
  - docker push stefan1982/multi-nginx
  - docker push stefan1982/multi-server
  - docker push stefan1982/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker4
  env: Multi-docker4-env
  bucket_name: elasticbeanstalk-us-east-1-792968057995
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
